/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "hsl(var(--on-secondary-fixed-variant))",
        "surface-container-low": "hsl(var(--surface-container-low))",
        "surface-tint": "hsl(var(--surface-tint))",
        "secondary-fixed": "hsl(var(--secondary-fixed))",
        "on-primary-container": "hsl(var(--on-primary-container))",
        "on-tertiary": "hsl(var(--on-tertiary))",
        "inverse-primary": "hsl(var(--inverse-primary))",
        "surface-container": "hsl(var(--surface-container))",
        "surface-dim": "hsl(var(--surface-dim))",
        "on-error-container": "hsl(var(--on-error-container))",
        "error": "hsl(var(--error))",
        "on-background": "hsl(var(--on-background))",
        "primary-fixed-dim": "hsl(var(--primary-fixed-dim))",
        "on-surface": "hsl(var(--on-surface))",
        "surface-bright": "hsl(var(--surface-bright))",
        "on-tertiary-container": "hsl(var(--on-tertiary-container))",
        "on-primary-fixed": "hsl(var(--on-primary-fixed))",
        "on-secondary-fixed": "hsl(var(--on-secondary-fixed))",
        "tertiary-container": "hsl(var(--tertiary-container))",
        "outline-variant": "hsl(var(--outline-variant))",
        "surface-container-high": "hsl(var(--surface-container-high))",
        "on-tertiary-fixed-variant": "hsl(var(--on-tertiary-fixed-variant))",
        "inverse-surface": "hsl(var(--inverse-surface))",
        "primary-fixed": "hsl(var(--primary-fixed))",
        "on-surface-variant": "hsl(var(--on-surface-variant))",
        "tertiary-fixed-dim": "hsl(var(--tertiary-fixed-dim))",
        "tertiary": "hsl(var(--tertiary))",
        "surface-variant": "hsl(var(--surface-variant))",
        "surface": "hsl(var(--surface))",
        "primary": "hsl(var(--primary))",
        "on-primary-fixed-variant": "hsl(var(--on-primary-fixed-variant))",
        "on-error": "hsl(var(--on-error))",
        "secondary": "hsl(var(--secondary))",
        "on-tertiary-fixed": "hsl(var(--on-tertiary-fixed))",
        "secondary-fixed-dim": "hsl(var(--secondary-fixed-dim))",
        "tertiary-fixed": "hsl(var(--tertiary-fixed))",
        "surface-container-lowest": "hsl(var(--surface-container-lowest))",
        "error-container": "hsl(var(--error-container))",
        "background": "hsl(var(--background))",
        "on-primary": "hsl(var(--on-primary))",
        "secondary-container": "hsl(var(--secondary-container))",
        "primary-container": "hsl(var(--primary-container))",
        "on-secondary": "hsl(var(--on-secondary))",
        "inverse-on-surface": "hsl(var(--inverse-on-surface))",
        "surface-container-highest": "hsl(var(--surface-container-highest))",
        "outline": "hsl(var(--outline))",
        "on-secondary-container": "hsl(var(--on-secondary-container))",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "64px",
        gutter: "32px",
        unit: "8px",
        "section-gap": "120px",
        "margin-mobile": "20px",
        "container-max": "1280px",
      },
      fontFamily: {
        "display-lg": ["Playfair Display", "serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.7", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "500" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.8", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "500" }],
      },
      keyframes: {
        fadeInUp: {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-in-up": "fadeInUp 0.8s ease forwards",
      },
    },
  },
  plugins: [],
};
